# Generated by Django 2.1.5 on 2020-06-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likes', models.IntegerField()),
                ('Contenu', models.TextField()),
                ('Date_pub', models.DateTimeField(blank=True, null=True)),
                ('Reponse', models.ManyToManyField(to='list.Commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=75)),
                ('Type_Plat', models.CharField(choices=[('Soupe', 'Soupe'), ('Salade', 'Salade'), ('Plat Principal', 'Plat Principal'), ('Dessert', 'Dessert')], max_length=20)),
                ('ingredients', models.TextField()),
                ('Type_cuisine', models.CharField(choices=[('Cuisine Traditionnelle', 'Cuisine Traditionnelle'), ('Nouvelle Cuisine', 'Nouvelle Cuisine'), ('Cuisine Exotique', 'Cuisine Exotique'), ('Cuisine Gastronomique', 'Cuisine Gastronomique'), ('Cuisine Moléculaire', 'Cuisine Moléculaire')], max_length=50)),
                ('image', models.ImageField(upload_to='static\\media')),
                ('prix', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Restau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=20)),
                ('Adresse', models.CharField(max_length=50)),
                ('Origine_cuisine', models.CharField(choices=[('Cuisine Française', 'Cuisine Française'), ('Cuisine Marocaine', 'Cuisine Marocaine'), ('Cuisine Japonaise', 'Cuisine Japonaise'), ('Cuisine Italienne', 'Cuisine Italienne'), ('Cuisine Mexicaine', 'Cuisine Mexicaine'), ('Cuisine Grecque', 'Cuisine Grecque')], max_length=50)),
                ('Details', models.TextField()),
                ('Votes', models.IntegerField(default=0)),
                ('images', models.TextField()),
                ('Plats', models.ManyToManyField(to='list.Plat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=75)),
                ('Nom', models.CharField(max_length=20)),
                ('MotPasse', models.CharField(max_length=20)),
                ('Adresse', models.CharField(max_length=50)),
                ('Date_ajout', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='commentaire',
            name='Restau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Restau'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.User'),
        ),
    ]
