# Generated by Django 2.1.5 on 2020-06-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200616_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='Type_Plat',
            field=models.CharField(choices=[('Soupe', 'Soupe'), ('Salade', 'Salade'), ('Autre Entree', 'Autre Entree'), ('Plat Principal', 'Plat Principal'), ('Dessert', 'Dessert')], max_length=20),
        ),
    ]
