# Generated by Django 2.1.5 on 2020-06-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20200616_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Sans Gluten', 'Sans Gluten'), ('Vegan', 'Vegan'), ('Végétarien', 'Végétarien'), ('Riche en protéines', 'Riche en protéines'), ('Normal', 'Normal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='plat',
            name='Type_cuisine',
            field=models.CharField(blank=True, choices=[('Cuisine Traditionnelle', 'Cuisine Traditionnelle'), ('Nouvelle Cuisine', 'Nouvelle Cuisine'), ('Cuisine Exotique', 'Cuisine Exotique'), ('Cuisine Gastronomique', 'Cuisine Gastronomique'), ('Cuisine Moléculaire', 'Cuisine Moléculaire')], max_length=50),
        ),
    ]
