# Generated by Django 2.1.5 on 2020-06-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20200617_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plat',
            name='categorie',
            field=models.CharField(blank=True, choices=[('Sans Gluten', 'Sans Gluten'), ('Vegan', 'Vegan'), ('Végétarien', 'Végétarien'), ('Riche en protéines', 'Riche en protéines'), ('Normal', 'Normal')], max_length=2),
        ),
        migrations.RemoveField(
            model_name='restau',
            name='images',
        ),
        migrations.AddField(
            model_name='restau',
            name='images',
            field=models.ManyToManyField(blank=True, to='list.image'),
        ),
    ]
