# Generated by Django 2.2 on 2020-06-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200618_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Reponse',
            field=models.ManyToManyField(blank=True, to='list.Commentaire'),
        ),
    ]
