# Generated by Django 2.2 on 2020-06-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200618_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Adresse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Date_ajout',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MotPasse',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
