# Generated by Django 2.2 on 2020-06-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_auto_20200618_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=2),
        ),
    ]
