# Generated by Django 2.2 on 2020-06-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20200619_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Reponse',
            field=models.ManyToManyField(blank=True, related_name='_commentaire_Reponse_+', to='list.Commentaire'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
