# Generated by Django 2.2 on 2020-06-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_auto_20200620_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
