# Generated by Django 2.2 on 2020-07-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0022_auto_20200701_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponse',
            name='Com',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='User',
        ),
        migrations.RemoveField(
            model_name='restau',
            name='HeuresTrv',
        ),
        migrations.RemoveField(
            model_name='restau',
            name='Plats',
        ),
        migrations.RemoveField(
            model_name='restau',
            name='images',
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
        migrations.DeleteModel(
            name='HeuresTravail',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='Plat',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.DeleteModel(
            name='Restau',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
