# Generated by Django 2.2 on 2020-07-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_auto_20200702_1316'),
        ('list', '0025_auto_20200720_1415'),
    ]

    operations = [
    ]
